class Activities {
  final String title;
  final String id;

  Activities({ this.title, this.id });
}

final List<Activities> activities = <Activities>[
  Activities(title: 'Celebrating...', id: 'celebrating'),
  Activities(title: 'Watching...', id: 'watching'),
  Activities(title: 'Eating...', id: 'eating'),
  Activities(title: 'Drinking...', id: 'drinking'),
  Activities(title: 'Attending...', id: 'attending'),
  Activities(title: 'Travelling to...', id: 'travelling'),
  Activities(title: 'Listening to...', id: 'listening'),
  Activities(title: 'Looking for...', id: 'looking'),
  Activities(title: 'Thinking about...', id: 'thinking'),
  Activities(title: 'Reading...', id: 'reading'),
  Activities(title: 'Playing...', id: 'playing'),
  Activities(title: 'Supporting...', id: 'supporting')
];

final List<Activities> thinking = <Activities>[
  Activities(title: 'old memories', id: 'thinking'),
  Activities(title: 'the meaning of life', id: 'thinking'),
  Activities(title: 'making a change', id: 'thinking'),
  Activities(title: 'my future', id: 'thinking'),
  Activities(title: 'someone special', id: 'thinking'),
  Activities(title: 'a lot of things', id: 'thinking'),
  Activities(title: 'doing something different', id: 'thinking'),
  Activities(title: 'all the good times', id: 'thinking'),
  Activities(title: 'life', id: 'thinking'),
  Activities(title: 'friends and family', id: 'thinking'),
  Activities(title: 'better days', id: 'thinking'),
  Activities(title: 'a holiday', id: 'thinking'),
  Activities(title: 'doing something crazy', id: 'thinking'),
  Activities(title: 'my mum', id: 'thinking'),
  Activities(title: 'my son', id: 'thinking'),
  Activities(title: 'my daughter', id: 'thinking'),
  Activities(title: 'all my friends', id: 'thinking'),
  Activities(title: 'my birthday', id: 'thinking'),
  Activities(title: 'tomorrow', id: 'thinking'),
  Activities(title: 'my girlfriend', id: 'thinking'),
  Activities(title: 'going back to school', id: 'thinking'),
  Activities(title: 'buying a car', id: 'thinking'),
];

final List<Activities> looking = <Activities>[
  Activities(title: 'advice', id: 'looking'),
  Activities(title: 'help', id: 'looking'),
  Activities(title: 'a miracle', id: 'looking'),
  Activities(title: 'answers', id: 'looking'),
  Activities(title: 'ideas', id: 'looking'),
  Activities(title: 'prayers', id: 'looking'),
  Activities(title: 'perfection', id: 'looking'),
  Activities(title: 'birthday present recommendations', id: 'looking'),
  Activities(title: 'Nessie', id: 'looking'),
  Activities(title: 'balance', id: 'looking'),
  Activities(title: 'travel recommendations', id: 'looking'),
  Activities(title: 'a trip', id: 'looking'),
  Activities(title: 'an angel', id: 'looking'),
  Activities(title: 'cuddles', id: 'looking'),
  Activities(title: 'donations', id: 'looking'),
  Activities(title: 'dinosaurs', id: 'looking'),
  Activities(title: 'easy money', id: 'looking'),
  Activities(title: 'ufos', id: 'looking'),
  Activities(title: 'Bigfoot', id: 'looking'),
  Activities(title: 'a boyfriend', id: 'looking'),
  Activities(title: 'a mobile phone', id: 'looking'),
  Activities(title: 'great music', id: 'looking'),
  Activities(title: 'shoes', id: 'looking'),
  Activities(title: 'film recommendations', id: 'looking'),
  Activities(title: 'a full-time employee', id: 'looking'),
  Activities(title: 'a housemate', id: 'looking'),
  Activities(title: 'a Christmas tree', id: 'looking'),
  Activities(title: 'a doctor', id: 'looking'),
  Activities(title: 'restuarant recommendations', id: 'looking'),
  Activities(title: 'a car', id: 'looking'),
  Activities(title: 'photographer recommendations', id: 'looking'),
  Activities(title: 'a dog', id: 'looking'),
  Activities(title: 'dentist recommendations', id: 'looking'),
  Activities(title: 'a beer', id: 'looking'),
  Activities(title: 'food', id: 'looking'),
  Activities(title: 'a babysitter', id: 'looking'),
  Activities(title: 'job recommendations', id: 'looking'),
  Activities(title: 'a kind soul', id: 'looking'),
  Activities(title: 'doctor recommendations', id: 'looking'),
  Activities(title: 'a tattoo artist', id: 'looking'),
  Activities(title: 'food recommendations', id: 'looking'),
  Activities(title: 'ice cream', id: 'looking'),
  Activities(title: 'the holy grail', id: 'looking'),
  Activities(title: 'a workout', id: 'looking'),
  Activities(title: 'car recommendations', id: 'looking'),
];

final List<Activities> attending = <Activities>[
  Activities(title: 'church', id: 'attending'),
  Activities(title: 'a wedding', id: 'attending'),
  Activities(title: 'an event', id: 'attending'),
  Activities(title: 'a birthday party', id: 'attending'),
  Activities(title: 'a Christmas party', id: 'attending'),
  Activities(title: 'work', id: 'attending'),
  Activities(title: 'a live concert', id: 'attending'),
  Activities(title: 'a meeting', id: 'attending'),
  Activities(title: 'Sunday mass', id: 'attending'),
  Activities(title: 'a marriage ceremony', id: 'attending'),
  Activities(title: 'a training', id: 'attending'),
  Activities(title: 'mass', id: 'attending'),
  Activities(title: 'a basketball game', id: 'attending'),
  Activities(title: 'a seminar', id: 'attending'),
  Activities(title: 'a wedding reception', id: 'attending'),
  Activities(title: 'a party', id: 'attending'),
  Activities(title: 'a conference', id: 'attending'),
  Activities(title: 'school/college/university', id: 'attending'),
];

final List<Activities> celebrating = <Activities>[
  Activities(title: 'friendship', id: 'celebrating'),
  Activities(title: 'a birthday', id: 'celebrating'),
  Activities(title: 'your special day', id: 'celebrating'),
  Activities(title: 'birthdays', id: 'celebrating'),
  Activities(title: 'Christmas', id: 'celebrating'),
  Activities(title: "New Year's Eve", id: 'celebrating'),
  Activities(title: "this special day", id: 'celebrating'),
  Activities(title: "my brother's birthday", id: 'celebrating'),
  Activities(title: "the Queen's birthday", id: 'celebrating'),
  Activities(title: "my sister's birthday", id: 'celebrating'),
  Activities(title: "my birthday", id: 'celebrating'),
  Activities(title: "success", id: 'celebrating'),
  Activities(title: "the holidays", id: 'celebrating'),
  Activities(title: "another year of life", id: 'celebrating'),
  Activities(title: "our wedding anniversary", id: 'celebrating'),
  Activities(title: "love", id: 'celebrating'),
  Activities(title: "my mum's birthday", id: 'celebrating'),
  Activities(title: "life", id: 'celebrating'),
  Activities(title: "another year", id: 'celebrating'),
  Activities(title: "Thanksgiving", id: 'celebrating'),
  Activities(title: "victory", id: 'celebrating'),
  Activities(title: "my dad's birthday", id: 'celebrating'),
  Activities(title: "this day", id: 'celebrating'),
  Activities(title: "holidays", id: 'celebrating'),
  Activities(title: "Makar Sankranti", id: 'celebrating'),
  Activities(title: "our anniversary", id: 'celebrating'),
  Activities(title: "your big day", id: 'celebrating'),
  Activities(title: "our special day", id: 'celebrating'),
  Activities(title: "another birthday", id: 'celebrating'),
  Activities(title: "graduation", id: 'celebrating'),
  Activities(title: "engagement", id: 'celebrating'),
  Activities(title: "Pongal", id: 'celebrating'),
  Activities(title: "your day", id: 'celebrating'),
  Activities(title: "their birthdays", id: 'celebrating'),
  Activities(title: "the season", id: 'celebrating'),
  Activities(title: "my special day", id: 'celebrating'),
];