class Feelings {
  final String title;

  Feelings({ this.title });
}

final List<Feelings> feelings = <Feelings>[
  Feelings(title: 'happy'), Feelings(title: 'blessed'),
  Feelings(title: 'loved'), Feelings(title: 'sad'),
  Feelings(title: 'lovely'), Feelings(title: 'thankful'),
  Feelings(title: 'excited'), Feelings(title: 'in love'),
  Feelings(title: 'crazy'), Feelings(title: 'grateful'),
  Feelings(title: 'blissful'), Feelings(title: 'fantastic'),
  Feelings(title: 'silly'), Feelings(title: 'festive'),
  Feelings(title: 'wonderful'), Feelings(title: 'cool'),
  Feelings(title: 'amused'), Feelings(title: 'relaxed'),
  Feelings(title: 'positive'), Feelings(title: 'chill'),
  Feelings(title: 'hopeful'), Feelings(title: 'joyful'),
  Feelings(title: 'tired'), Feelings(title: 'motivated'),
  Feelings(title: 'proud'), Feelings(title: 'alone'),
  Feelings(title: 'thoughtful'), Feelings(title: 'OK'),
  Feelings(title: 'nostalgic'), Feelings(title: 'angry'),
  Feelings(title: 'sick'), Feelings(title: 'delighted'),
  Feelings(title: 'drained'), Feelings(title: 'emotional'),
  Feelings(title: 'confident'), Feelings(title: 'awesome'),
  Feelings(title: 'fresh'), Feelings(title: 'determined'),
  Feelings(title: 'exhausted'), Feelings(title: 'annoyed'),
  Feelings(title: 'glad'), Feelings(title: 'lucky'),
  Feelings(title: 'heartbroken'), Feelings(title: 'bored'),
  Feelings(title: 'sleepy'), Feelings(title: 'energised'),
  Feelings(title: 'hungry'), Feelings(title: 'professional'),
  Feelings(title: 'pained'), Feelings(title: 'peaceful'),
  Feelings(title: 'disappointed'), Feelings(title: 'optimistic'),
  Feelings(title: 'cold'), Feelings(title: 'cute'),
  Feelings(title: 'fabulous'), Feelings(title: 'great'),
  Feelings(title: 'sorry'), Feelings(title: 'super'),
  Feelings(title: 'worried'), Feelings(title: 'funny'),
  Feelings(title: 'bad'), Feelings(title: 'down'),
  Feelings(title: 'inspired'), Feelings(title: 'satisfied'),
  Feelings(title: 'pumped'), Feelings(title: 'calm'),
  Feelings(title: 'confused'), Feelings(title: 'goofy'),
  Feelings(title: 'missing'), Feelings(title: 'good'),
  Feelings(title: 'sarcastic'), Feelings(title: 'lonely'),
  Feelings(title: 'strong'), Feelings(title: 'concerned'),
  Feelings(title: 'special'), Feelings(title: 'depressed'),
  Feelings(title: 'jolly'), Feelings(title: 'curious'),
  Feelings(title: 'low'), Feelings(title: 'welcome'),
  Feelings(title: 'broken'), Feelings(title: 'beautiful'),
  Feelings(title: 'amazing'), Feelings(title: 'irritated'),
  Feelings(title: 'stressed'), Feelings(title: 'incomplete'),
  Feelings(title: 'hyper'), Feelings(title: 'mischievous'),
  Feelings(title: 'amazed'), Feelings(title: 'annoyed'),
  Feelings(title: 'fed up'), Feelings(title: 'puzzled'),
  Feelings(title: 'furious'), Feelings(title: 'refreshed'),
  Feelings(title: 'accomplished'), Feelings(title: 'surprised'),
  Feelings(title: 'frustrated'), Feelings(title: 'perplexed'),
  Feelings(title: 'meh'), Feelings(title: 'pretty'),
  Feelings(title: 'guilty'), Feelings(title: 'better'),
  Feelings(title: 'safe'), Feelings(title: 'free'),
  Feelings(title: 'old'), Feelings(title: 'lost'),
  Feelings(title: 'lazy'), Feelings(title: 'worse'),
  Feelings(title: 'comfortable'), Feelings(title: 'horrible'),
  Feelings(title: 'stupid'), Feelings(title: 'ashamed'),
  Feelings(title: 'asleep'), Feelings(title: 'terrible'),
  Feelings(title: 'well'), Feelings(title: 'alive'),
  Feelings(title: 'rough'), Feelings(title: 'shy'),
  Feelings(title: 'weird'), Feelings(title: 'human'),
  Feelings(title: 'awful'), Feelings(title: 'hurt'),
];